CREATE DATABASE EVENTS;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS EVENTS_HEADER (
    id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
    name VARCHAR NOT NULL, 
    type VARCHAR NOT NULL, 
    highlight BOOLEAN NOT NULL, 
    completed BOOLEAN NOT NULL, 
    startDateTime TIMESTAMP, 
    lastUpdateDateTime TIMESTAMP
);

DROP TABLE EVENTS_HEADER;
